import type { Metadata } from "next";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { Providers } from "./providers";
import { Poppins } from "next/font/google";
import {Header} from "../components/header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${poppins.className} antialiased`}>
      <Providers>
        <div className="flex flex-col w-full h-screen">
            <Header/>
          {children}
        </div>
      </Providers>
      </body>
      </html>
  );
}
