"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const auth_controller_1 = require("../controllers/auth.controller");
const router = (0, express_1.Router)();
router.post("/nonce", auth_controller_1.getNonce);
router.post("/verify", auth_controller_1.verifySignature);
router.use(auth_middleware_1.authMiddleware);
router.get("/me", auth_controller_1.getMe);
router.put("/profile", auth_controller_1.updateProfile);
exports.default = router;
