"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const chat_controller_1 = require("../controllers/chat.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.use(auth_middleware_1.authMiddleware);
router.post('/', chat_controller_1.createChat);
router.get('/', chat_controller_1.getChats);
router.get('/:id', chat_controller_1.getChat);
router.delete('/:id', chat_controller_1.deleteChat);
router.post('/:id/send', chat_controller_1.sendMessage);
exports.default = router;
