"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const developer_controller_1 = require("../controllers/developer.controller");
const router = (0, express_1.Router)();
router.use(auth_middleware_1.authMiddleware);
router.post("/keys", developer_controller_1.createKey);
router.get("/keys", developer_controller_1.getKeys);
router.delete("/keys/:id", developer_controller_1.deleteKey);
exports.default = router;
